seed: 1
record_video: yes

environment:
  render: True
  #  for training
  num_envs: 50
  eval_every_n: 30
  max_time: 10.01 # max_time larger than 10 is required to observe draws.


  plot_metric_n: 10

  num_threads: 32
  simulation_dt: 0.0025
  control_dt: 0.01
  action_std: 0.3
